### ISSUE TITLE
Unclear functional description A001

### ISSUE THREAD

**Issue by monty241** [AnalyticsLibrary/Analytics#4]
The sample A001 lists both:

- Saldibalans per periode
- Mutaties per periode

The first one is a total across time, the second one is in/outflow. What is the correct specification?

**Comment by JorisJoppe** [comment]
Added clarification - 

- balans is cumulatief (om balanspost per periode te kunnen berekenen)
- resultatenrekening is stroomgrootheid dus simpelweg de totalen per periode.

Zie [hier](https://github.com/AnalyticsLibrary/Analytics/wiki/A001-Mutaties-per-periode)
